### ISSUE TITLE
SHARP_MIP.h typos

### ISSUE THREAD

**Issue by elektronchika** [littlevgl/lv_drivers#80]
Line 46 should be:

`void sharp_mip_flush(lv_disp_drv_t * disp_drv, const lv_area_t * area, lv_color_t * color_p);`

Line 50 should be:

`void sharp_mip_com_inversion(void);`

**Comment by kisvegabor** [comment]
Can you send a Pull request?
If no I can also add it but it might be useful to learn how the creat Pull requests. :wink: 

Here you can read about it: https://blog.littlevgl.com/2018-12-06/contributing

Of course, you need to fork `lv_drivers` instead of `lvgl` and you can leave the base brach as `master`.

**Comment by embeddedt** [comment]
PR merged. Closing as the OP stated the code compiles now.

**Comment by kisvegabor** [comment]
Thank you for the PR!
